export enum UserActionEvent {
  // ========== AUTH ==========
  LOGIN = "LOGIN",
  REFRESH_TOKEN_REQUESTED = "REFRESH_TOKEN_REQUESTED",
  ACCOUNT_DISABLED = "ACCOUNT_DISABLED",
  TAX_REGIME_UPDATED = "TAX_REGIME_UPDATED",
  PROFILE_PICTURE_UPDATED = "PROFILE_PICTURE_UPDATED",
  DOCUMENTS_UPDATED = "DOCUMENTS_UPDATED",

  CUSTOMER_CREATED = "CUSTOMER_CREATED",
  CUSTOMER_UPDATED = "CUSTOMER_UPDATED",
  CUSTOMERS_UPDATED_MANY = "CUSTOMERS_UPDATED_MANY",
  CUSTOMER_DELETED = "CUSTOMER_DELETED",

  USER_ADDED = "USER_ADDED",
  USER_DELETED = "USER_DELETED",
  USER_PERMISSION_UPDATED = "USER_PERMISSION_UPDATED",
  USER_PERMISSION_REMOVED = "USER_PERMISSION_REMOVED",

  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",

  // ========== CREDIT ==========
  CREDIT_WITHDRAWAL_REQUESTED = "CREDIT_WITHDRAWAL_REQUESTED",
  CREDIT_DEPOSIT = "CREDIT_DEPOSIT",

  // ========== INVOICE ==========
  INVOICE_CREATED = "INVOICE_CREATED",
  INVOICES_CREATED_MANY = "INVOICES_CREATED_MANY",
  INVOICE_RENEWED = "INVOICE_RENEWED",
  INVOICE_DELETED = "INVOICE_DELETED",
  INVOICE_INSTALLMENT_DELETED = "INVOICE_INSTALLMENT_DELETED",
  INVOICE_PAYMENT_CONFIRMED = "INVOICE_PAYMENT_CONFIRMED",
  INVOICE_PAYMENTS_CONFIRMED_MANY = "INVOICE_PAYMENTS_CONFIRMED_MANY",

  INVOICE_GROUP_CREATED = "INVOICE_GROUP_CREATED",
  INVOICE_GROUP_DELETED = "INVOICE_GROUP_DELETED",
  INVOICE_GROUP_CUSTOMER_LINKED = "INVOICE_GROUP_CUSTOMER_LINKED",

  // ========== PRODUCT ==========
  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  PRODUCT_DELETED = "PRODUCT_DELETED",

  PUBLIC_PRODUCT_CREATED = "PUBLIC_PRODUCT_CREATED", // quando o produto é tornado público
  PUBLIC_PRODUCT_UPDATED = "PUBLIC_PRODUCT_UPDATED",
  PUBLIC_PRODUCT_DELETED = "PUBLIC_PRODUCT_DELETED",
  PUBLIC_PRODUCT_PUBLISHED = "PUBLIC_PRODUCT_PUBLISHED", // produto público publicado (visível na loja)
}
